
export const INITIAL_POPULATION = 5;
export const INITIAL_FOOD = 100;
export const INITIAL_GOLD = 100;

export const GAMEBOX_HEIGHT = 1000;
export const GAMEBOX_WIDTH = 2000;


export const TOWNHALL_LENGHT = 200;

//Object colors
export const PLAYER_ONE_COLOR = "#457b9d";
export const PLAYER_TWO_COLOR = "#e63946";
export const GOLD_MINE_COLOR = "#f9dc5c";
export const FARM_COLOR = "#386641";

//P1 TOWNHALL CONST
export const P1_TOWNHALL_POSITION_X = 0;
export const P1_TOWNHALL_POSITION_Y = 0;
export const P1_TEXT_X = TOWNHALL_LENGHT / 2 - 75;
export const P1_TEXT_Y = TOWNHALL_LENGHT / 2 + 10;
//P2 TOWNHALL CONST
export const P2_TOWNHALL_POSITION_X = GAMEBOX_WIDTH - TOWNHALL_LENGHT;
export const P2_TOWNHALL_POSITION_Y = GAMEBOX_HEIGHT - TOWNHALL_LENGHT;
export const P2_TOWNHALL_TEXT_X = GAMEBOX_WIDTH - TOWNHALL_LENGHT / 2 - 60;
export const P2_TOWNHALL_TEXT_Y = GAMEBOX_HEIGHT - TOWNHALL_LENGHT / 2 + 20;
//GOLDMINE CONST
export const GOLDMINE_WIDTH = 350;
export const GOLDMINE_HEIGHT = 250;
export const GOLDMINE_POSITION_X = GAMEBOX_WIDTH - GOLDMINE_WIDTH;
export const GOLDMINE_POSITION_Y = 0;
export const GOLDMINE_TEXT_X = GAMEBOX_WIDTH - GOLDMINE_WIDTH / 2 - 55;
export const GOLDMINE_TEXT_Y = GOLDMINE_HEIGHT / 2 + 10;
//FARM CONST
export const FARM_WIDTH = 350;
export const FARM_HEIGHT = 250;
export const FARM_POSITION_X = 0;
export const FARM_POSITION_Y = GAMEBOX_HEIGHT - FARM_HEIGHT;
export const FARM_TEXT_X = FARM_WIDTH / 2 - 55;
export const FARM_TEXT_Y = FARM_POSITION_Y + FARM_HEIGHT / 2 + 20;

//PERSON CONST
export const PERSON_COST = 10;
export const VILLAGER_SIZE = 20;
export const SOLDIER_SIZE = 40;